name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build
        run: |
          mkdir -p bin
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/securitydns-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} ./cmd/main.go

      - name: Create .deb Package (Debian/Ubuntu)
        if: matrix.os == 'linux'
        run: |
          VERSION=${{ github.ref_name }}  # Extract tag name (v1.0.2)
          VERSION=${VERSION#v}  # Remove "v" prefix if present
          mkdir -p package/DEBIAN
          echo "Package: securitydns" > package/DEBIAN/control
          echo "Version: $VERSION" >> package/DEBIAN/control
          echo "Section: utils" >> package/DEBIAN/control
          echo "Priority: optional" >> package/DEBIAN/control
          echo "Architecture: ${{ matrix.arch }}" >> package/DEBIAN/control
          echo "Depends: libc6" >> package/DEBIAN/control
          echo "Maintainer: Stepan Kutaj <stepan.kutaj@tldr-it.com>" >> package/DEBIAN/control
          echo "Description: DNS Security Utils package" >> package/DEBIAN/control
          mkdir -p package/usr/local/bin
          cp bin/securitydns-linux-${{ matrix.arch }} package/usr/local/bin/securitydns
          chmod 755 package/usr/local/bin/securitydns
          dpkg-deb --build package securitydns-${{ matrix.arch }}.deb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: securitydns-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            bin/securitydns-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
            securitydns-${{ matrix.arch }}.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This permission is needed to create releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}